### ISSUE TITLE
ltc wont validate

### ISSUE THREAD

**Issue by rootb13** [christsim/multicoin-address-validator#10]
Hi, i currently use your package!!

Is it possible to add compatibility for litecoin addresses with "ltc1" prefix?

When validating the address responds false.

wav.validate('ltc1q00045kp4d4t884428ua6j6tncx6g405y7epwju', 'ltc');
false

Thanks!

**Comment by sarahakhtar** [comment]
We're also facing this issue.

**Comment by HashEngineering** [comment]
That is because bech32 addresses are only currently supported for bitcoin.

See this line here:  
https://github.com/christsim/multicoin-address-validator/blob/master/src/crypto/segwit_addr.js#L74

Ideally, the hrp for each coin should be specified in the `src/currencies.js` file.

**Comment by rraina** [comment]
@HashEngineering @sarahakhtar -- facing the same issue, and came to same root cause. @christsim are you open to accepting a PR for this?

**Comment by rraina** [comment]
@christsim thank you for being open to a PR. I have made the requisite changes here: #22 . 

I tried to keep the changes minimal, and follow the pattern already in the code. That being said, there is some opportunity to use babel to make the code more modern.
