### ISSUE TITLE
BTC address not recognized

### ISSUE THREAD

**Issue by jaguarqc** [christsim/multicoin-address-validator#28]
1HVDCg2KrPBH1Mg5SK9fGjAR9KVqyMMdBC  is considered invalid but is a perfectly legal BTC address 

https://www.blockchain.com/btc/address/1HVDCg2KrPBH1Mg5SK9fGjAR9KVqyMMdBC report it valid

Any specific reason?

**Comment by christsim** [comment]
I can't reproduce, I've also added it to the unit tests.  Is this still a problem?
