### ISSUE TITLE
Add polkadot address validation

### ISSUE THREAD

**Issue by ArthurBrito** [christsim/multicoin-address-validator#39]
[Motivation:
](https://www.coingecko.com/en/coins/polkadot
)
Polkadot is currently ranked 8 market cap-wise. And It's a very promising project.

[Address format:
](https://wiki.polkadot.network/docs/en/learn-accounts)
The address format used in Substrate-based chains is SS58. SS58 is a modification of Base-58-check from Bitcoin with some minor modifications. Notably, the format contains an address type prefix that identifies an address as belonging to a specific network.

For example:

Polkadot addresses always start with the number 1.
Kusama addresses always start with a capital letter like C, D, F, G, H, J...
Generic Substrate addresses start with 5.
These prefixes are defined [here
](https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58))

**Comment by christsim** [comment]
Thanks.  Will add this to my backlog.

**Comment by ArthurBrito** [comment]
Update 18/01/21. Polkadot's price has skyrocketed and became the 4th biggest cryptocurrency in the world.

**Comment by christsim** [comment]
Was include in version multicoin-address-validator@0.4.16
please let me know if it working for you

**Comment by ArthurBrito** [comment]
Thanks for the update! Only a small detail, however, you forgot to update the README.md to include Dot :)
