### ISSUE TITLE
Stellar testnet validation issue

### ISSUE THREAD

**Issue by KmaCoder** [christsim/multicoin-address-validator#42]
Hi! Stellar testnet address [GCCVYKDNQP7NGNTR42SYPMQUZIFTPJUJHXM6JIXQMDLXMCC3ZYOV6AG3](https://stellar.expert/explorer/testnet/account/GCCVYKDNQP7NGNTR42SYPMQUZIFTPJUJHXM6JIXQMDLXMCC3ZYOV6AG3) is validated as invalid.

### Steps to reproduce:
`validate('GCCVYKDNQP7NGNTR42SYPMQUZIFTPJUJHXM6JIXQMDLXMCC3ZYOV6AG3', 'xlm', 'testnet')` returns false

### Expected behavior:
To return true

**Comment by KmaCoder** [comment]
The `computedChecksum` and `checksum` are different in `stellar_validator.js:42`

**Comment by chmmmr** [comment]
Thanks.  I found the issue,  will be fixed in 0.5+
